name: Build .NET Core

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '3.0.100', '3.1.100' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Restore
      run: dotnet restore
      working-directory: ./src
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src
